### ISSUE TITLE
Freebuds 3i support

### ISSUE THREAD

**Issue by Zac06** [melianmiko/OpenFreebuds#46] opened 2024-10-30 19:37 UTC
It would be great if the app could provide freebuds 3i support.

**Comment by melianmiko** [comment] 2024-10-31 11:16
Could try, if someone make a Bluetooth traffic dump & video as described in [this post](https://mmk.pw/en/posts/ofb-contribution/).

**Comment by melianmiko** [comment] 2024-10-31 11:17
Duplicate of #19, continue there.

**Closed by melianmiko** 2024-10-31 11:17 UTC
Labels: Device compatibility
